// prisma/seeds/04-tracks.ts
import type { PrismaClient, Album } from '@prisma/client'

/**
 * 트랙 시드 (앨범별 수록곡)
 */
export async function seedTracks(prisma: PrismaClient, albums: Album[]) {
  // 앨범 ID 매핑 (title로 찾기)
  const albumMap = Object.fromEntries(albums.map((a) => [a.title, a.id]))

  const tracks = [
    // ===== Hands Up (2곡) =====
    {
      albumId: albumMap['Hands Up'],
      trackNumber: 1,
      title: 'Hands Up',
      durationSec: 3 * 60 + 14,
      language: 'JAPANESE' as const,
      isTitle: true,
      isSingle: true,
      hasMv: true,
      mvUrl: 'https://youtu.be/ZVcy7bQkBhA?si=kkbr3kx4Hknp2h71',
      audioUrl: 'https://youtu.be/xB6LGMJG4So?si=lC-tV0m_N0pR_a9b',
      note: null,
    },
    {
      albumId: albumMap['Hands Up'],
      trackNumber: 2,
      title: 'We Go!',
      durationSec: 3 * 60 + 1,
      language: 'JAPANESE' as const,
      isTitle: false,
      isSingle: false,
      hasMv: false,
      mvUrl: null,
      audioUrl: null, // TODO: 추가
      note: null,
    },

    // ===== WISH (4곡) =====
    {
      albumId: albumMap['WISH'],
      trackNumber: 1,
      title: 'WISH (Korean Ver.)',
      durationSec: 3 * 60 + 26,
      language: 'KOREAN' as const,
      isTitle: true,
      isSingle: true,
      hasMv: true,
      mvUrl: 'https://www.youtube.com/watch?v=Rrf8uQFvICE',
      audioUrl: null,
      note: null,
    },
    {
      albumId: albumMap['WISH'],
      trackNumber: 2,
      title: 'WISH (Japanese Ver.)',
      durationSec: 3 * 60 + 26,
      language: 'JAPANESE' as const,
      isTitle: false,
      isSingle: false,
      hasMv: true,
      mvUrl: null,
      note: null,
    },
    {
      albumId: albumMap['WISH'],
      trackNumber: 3,
      title: 'NASA',
      durationSec: 3 * 60 + 11,
      language: 'KOREAN' as const,
      isTitle: false,
      isSingle: false,
      hasMv: false,
      mvUrl: null,
      audioUrl: null,
      note: null,
    },
    {
      albumId: albumMap['WISH'],
      trackNumber: 4,
      title: 'Dunk Shot',
      durationSec: 3 * 60 + 1,
      language: 'KOREAN' as const,
      isTitle: false,
      isSingle: false,
      hasMv: false,
      mvUrl: null,
      audioUrl: null,
      note: null,
    },

    // ===== Songbird (2곡) =====
    {
      albumId: albumMap['Songbird'],
      trackNumber: 1,
      title: 'Songbird',
      durationSec: 3 * 60 + 28,
      language: 'JAPANESE' as const,
      isTitle: true,
      isSingle: true,
      hasMv: true,
      mvUrl: 'https://www.youtube.com/watch?v=example',
      audioUrl: null,
      note: 'Japanese Version of WISH',
    },
    {
      albumId: albumMap['Songbird'],
      trackNumber: 2,
      title: 'Songbird (Instrumental)',
      durationSec: 3 * 60 + 28,
      language: 'OTHER' as const,
      isTitle: false,
      isSingle: false,
      hasMv: false,
      mvUrl: null,
      audioUrl: null,
      note: 'Instrumental Version',
    },

    // ===== Steady (7곡) =====
    {
      albumId: albumMap['Steady'],
      trackNumber: 1,
      title: 'Steady',
      durationSec: 3 * 60 + 9,
      language: 'KOREAN' as const,
      isTitle: true,
      isSingle: true,
      hasMv: true,
      mvUrl: 'https://www.youtube.com/watch?v=example',
      audioUrl: null,
      note: null,
    },
    {
      albumId: albumMap['Steady'],
      trackNumber: 2,
      title: 'Sail Away',
      durationSec: 2 * 60 + 56,
      language: 'KOREAN' as const,
      isTitle: false,
      isSingle: false,
      hasMv: false,
      mvUrl: null,
      audioUrl: null,
      note: null,
    },
    {
      albumId: albumMap['Steady'],
      trackNumber: 3,
      title: 'Tears Are Falling',
      durationSec: 3 * 60 + 9,
      language: 'KOREAN' as const,
      isTitle: false,
      isSingle: false,
      hasMv: false,
      mvUrl: null,
      audioUrl: null,
      note: null,
    },
    {
      albumId: albumMap['Steady'],
      trackNumber: 4,
      title: 'ON&ON',
      durationSec: 2 * 60 + 55,
      language: 'KOREAN' as const,
      isTitle: false,
      isSingle: false,
      hasMv: false,
      mvUrl: null,
      audioUrl: null,
      note: null,
    },
    {
      albumId: albumMap['Steady'],
      trackNumber: 5,
      title: 'Urgent',
      durationSec: 2 * 60 + 46,
      language: 'KOREAN' as const,
      isTitle: false,
      isSingle: false,
      hasMv: false,
      mvUrl: null,
      audioUrl: null,
      note: null,
    },
    {
      albumId: albumMap['Steady'],
      trackNumber: 6,
      title: 'Good Day',
      durationSec: 3 * 60 + 11,
      language: 'KOREAN' as const,
      isTitle: false,
      isSingle: false,
      hasMv: false,
      mvUrl: null,
      audioUrl: null,
      note: null,
    },
    {
      albumId: albumMap['Steady'],
      trackNumber: 7,
      title: 'WISH',
      durationSec: 3 * 60 + 12,
      language: 'KOREAN' as const,
      isTitle: false,
      isSingle: false,
      hasMv: false,
      mvUrl: null,
      audioUrl: null,
      note: 'Album Version',
    },

    // ===== WISHFUL (13곡) =====
    {
      albumId: albumMap['WISHFUL'],
      trackNumber: 1,
      title: 'Where We Are',
      durationSec: 3 * 60 + 5,
      language: 'JAPANESE' as const,
      isTitle: false,
      isSingle: false,
      hasMv: false,
      mvUrl: null,
      audioUrl: null,
      note: 'Intro Track',
    },
    {
      albumId: albumMap['WISHFUL'],
      trackNumber: 2,
      title: 'Hands Up',
      durationSec: 3 * 60 + 35,
      language: 'JAPANESE' as const,
      isTitle: false,
      isSingle: false,
      hasMv: true,
      mvUrl: null,
      audioUrl: null,
      note: null,
    },
    {
      albumId: albumMap['WISHFUL'],
      trackNumber: 3,
      title: 'Songbird',
      durationSec: 3 * 60 + 28,
      language: 'JAPANESE' as const,
      isTitle: true,
      isSingle: true,
      hasMv: true,
      mvUrl: null,
      audioUrl: null,
      note: null,
    },
    {
      albumId: albumMap['WISHFUL'],
      trackNumber: 4,
      title: 'Toki no Yukue',
      durationSec: 3 * 60 + 34,
      language: 'JAPANESE' as const,
      isTitle: false,
      isSingle: false,
      hasMv: false,
      mvUrl: null,
      audioUrl: null,
      note: null,
    },
    {
      albumId: albumMap['WISHFUL'],
      trackNumber: 5,
      title: 'Supernova',
      durationSec: 2 * 60 + 53,
      language: 'JAPANESE' as const,
      isTitle: false,
      isSingle: false,
      hasMv: false,
      mvUrl: null,
      audioUrl: null,
      note: null,
    },
    {
      albumId: albumMap['WISHFUL'],
      trackNumber: 6,
      title: 'Parade',
      durationSec: 3 * 60 + 1,
      language: 'JAPANESE' as const,
      isTitle: false,
      isSingle: false,
      hasMv: false,
      mvUrl: null,
      audioUrl: null,
      note: null,
    },
    {
      albumId: albumMap['WISHFUL'],
      trackNumber: 7,
      title: 'Crazy Summer',
      durationSec: 3 * 60 + 8,
      language: 'JAPANESE' as const,
      isTitle: false,
      isSingle: false,
      hasMv: false,
      mvUrl: null,
      audioUrl: null,
      note: null,
    },
    {
      albumId: albumMap['WISHFUL'],
      trackNumber: 8,
      title: 'Touchdown',
      durationSec: 2 * 60 + 42,
      language: 'JAPANESE' as const,
      isTitle: false,
      isSingle: false,
      hasMv: false,
      mvUrl: null,
      audioUrl: null,
      note: null,
    },
    {
      albumId: albumMap['WISHFUL'],
      trackNumber: 9,
      title: 'Sweet & Spicy',
      durationSec: 2 * 60 + 55,
      language: 'JAPANESE' as const,
      isTitle: false,
      isSingle: false,
      hasMv: false,
      mvUrl: null,
      audioUrl: null,
      note: null,
    },
    {
      albumId: albumMap['WISHFUL'],
      trackNumber: 10,
      title: 'Love Love Love',
      durationSec: 3 * 60 + 15,
      language: 'JAPANESE' as const,
      isTitle: false,
      isSingle: false,
      hasMv: false,
      mvUrl: null,
      audioUrl: null,
      note: null,
    },
    {
      albumId: albumMap['WISHFUL'],
      trackNumber: 11,
      title: 'Bokura no Uta',
      durationSec: 3 * 60 + 21,
      language: 'JAPANESE' as const,
      isTitle: false,
      isSingle: false,
      hasMv: false,
      mvUrl: null,
      audioUrl: null,
      note: null,
    },
    {
      albumId: albumMap['WISHFUL'],
      trackNumber: 12,
      title: 'Aurora',
      durationSec: 3 * 60 + 44,
      language: 'JAPANESE' as const,
      isTitle: false,
      isSingle: false,
      hasMv: false,
      mvUrl: null,
      audioUrl: null,
      note: null,
    },
    {
      albumId: albumMap['WISHFUL'],
      trackNumber: 13,
      title: 'WISHFUL',
      durationSec: 3 * 60 + 31,
      language: 'JAPANESE' as const,
      isTitle: false,
      isSingle: false,
      hasMv: false,
      mvUrl: null,
      audioUrl: null,
      note: 'Title Track',
    },
  ]

  for (const track of tracks) {
    const existing = await prisma.track.findFirst({
      where: {
        albumId: track.albumId,
        trackNumber: track.trackNumber,
      },
    })

    if (!existing) {
      await prisma.track.create({ data: track })
    }
  }

  console.log(`   ✓ Created ${tracks.length} tracks`)
}