// prisma/seeds/04-tracks.ts
import type { PrismaClient, Album, Track } from '@prisma/client'
import { logger, ProgressTracker } from './utils'

/**
 * 트랙 시드 (앨범별 수록곡)
 */
export async function seedTracks(prisma: PrismaClient, albums: Album[]): Promise<Track[]> {
  // 앨범 ID 매핑 (title로 찾기)
  const albumMap = Object.fromEntries(albums.map((a) => [a.title, a.id]))

  const tracks = [
    // ==================== Hands Up (2곡) ====================
    {
      albumId: albumMap['Hands Up'],
      trackNumber: 1,
      title: 'Hands Up',
      durationSec: 3 * 60 + 14,
      genre: 'Dance',
      language: 'JAPANESE' as const,
      isTitle: true,
      isSingle: false,
      isPreRelease: false,
      releaseDate: new Date('2023-10-08'),
      hasMv: true,
      mvUrl: 'https://youtu.be/ZVcy7bQkBhA',
      audioUrl: 'https://youtu.be/xB6LGMJG4So',
      note: 'Pre-debut title track',
    },
    {
      albumId: albumMap['Hands Up'],
      trackNumber: 2,
      title: 'We Go!',
      durationSec: 3 * 60 + 1,
      genre: 'Pop',
      language: 'JAPANESE' as const,
      isTitle: false,
      isSingle: false,
      isPreRelease: false,
      releaseDate: new Date('2023-10-08'),
      hasMv: false,
      audioUrl: 'https://youtu.be/iVEHidURFoU',
      note: null,
    },

    // ==================== WISH (4곡) ====================
    {
      albumId: albumMap['WISH'],
      trackNumber: 1,
      title: 'WISH (Korean Ver.)',
      durationSec: 3 * 60 + 5,
      genre: 'Dance',
      language: 'KOREAN' as const,
      isTitle: true,
      isSingle: false,
      isPreRelease: false,
      releaseDate: new Date('2024-02-28'),
      hasMv: true,
      mvUrl: 'https://youtu.be/hvQZs3k6Ytk',
      audioUrl: 'https://youtu.be/UrMOr7JCwbM',
      note: 'Debut title track Korean version',
    },
    {
      albumId: albumMap['WISH'],
      trackNumber: 2,
      title: 'WISH (Japanese Ver.)',
      durationSec: 3 * 60 + 5,
      genre: 'Dance',
      language: 'JAPANESE' as const,
      isTitle: true,
      isSingle: false,
      isPreRelease: false,
      releaseDate: new Date('2024-02-28'),
      hasMv: true,
      mvUrl: 'https://youtu.be/ZgrEZmAgzM8',
      audioUrl: 'https://youtu.be/9iGQcADfOtU',
      note: 'Debut title track Japanese version',
    },
    {
      albumId: albumMap['WISH'],
      trackNumber: 3,
      title: 'Sail Away (Korean Ver.)',
      durationSec: 3 * 60 + 25,
      genre: 'Pop',
      language: 'KOREAN' as const,
      isTitle: false,
      isSingle: false,
      isPreRelease: false,
      releaseDate: new Date('2024-02-28'),
      hasMv: false,
      audioUrl: 'https://youtu.be/VLtIZR4wHtU',
      note: 'Korean version',
    },
    {
      albumId: albumMap['WISH'],
      trackNumber: 4,
      title: 'Sail Away (Japanese Ver.)',
      durationSec: 3 * 60 + 25,
      genre: 'Pop',
      language: 'JAPANESE' as const,
      isTitle: false,
      isSingle: false,
      isPreRelease: false,
      releaseDate: new Date('2024-02-28'),
      hasMv: false,
      audioUrl: 'https://youtu.be/ne-rLStTjZg',
      note: 'Japanese version',
    },

    // ==================== Songbird (2곡) ====================
    {
      albumId: albumMap['Songbird'],
      trackNumber: 1,
      title: 'Songbird (Korean Ver.)',
      durationSec: 3 * 60 + 2,
      genre: 'Dance',
      language: 'KOREAN' as const,
      isTitle: true,
      isSingle: false,
      isPreRelease: false,
      releaseDate: new Date('2024-07-01'),
      hasMv: true,
      mvUrl: 'https://youtu.be/2XqVNFBtVo4',
      audioUrl: 'https://youtu.be/1wcQnFzozLI',
      note: 'Songbird title Korean version',
    },
    {
      albumId: albumMap['Songbird'],
      trackNumber: 2,
      title: 'Tears Are Falling (Korean Ver.)',
      durationSec: 3 * 60 + 5,
      genre: 'Ballad',
      language: 'KOREAN' as const,
      isTitle: false,
      isSingle: false,
      isPreRelease: false,
      releaseDate: new Date('2024-07-01'),
      hasMv: false,
      audioUrl: 'https://youtu.be/UxEdtQR7gUM',
      note: 'Korean version',
    },
    {
      albumId: albumMap['Songbird'],
      trackNumber: 3,
      title: 'Songbird (Japanese Ver.)',
      durationSec: 3 * 60 + 2,
      genre: 'Dance',
      language: 'JAPANESE' as const,
      isTitle: true,
      isSingle: false,
      isPreRelease: false,
      releaseDate: new Date('2024-06-25'),
      hasMv: true,
      mvUrl: 'https://youtu.be/C_qALZPuK8I',
      audioUrl: 'https://youtu.be/5kKZ53-uJCU',
      note: 'Songbird title Japanese version',
    },
    {
      albumId: albumMap['Songbird'],
      trackNumber: 4,
      title: 'Tears Are Falling (Japanese Ver.)',
      durationSec: 3 * 60 + 5,
      genre: 'Ballad',
      language: 'JAPANESE' as const,
      isTitle: false,
      isSingle: false,
      isPreRelease: false,
      releaseDate: new Date('2024-06-25'),
      hasMv: false,
      audioUrl: 'https://youtu.be/gKhf-U9l0nE',
      note: 'Japanese version',
    },

    // ==================== Steady (7곡) ====================
    {
      albumId: albumMap['Steady'],
      trackNumber: 1,
      title: 'Steady',
      durationSec: 3 * 60,
      genre: 'Dance',
      language: 'KOREAN' as const,
      isTitle: true,
      isSingle: false,
      isPreRelease: false,
      releaseDate: new Date('2024-09-24'),
      hasMv: true,
      mvUrl: 'https://youtu.be/IKlkZZv76Ho',
      audioUrl: 'https://youtu.be/mcFWD-sgi_Y',
      note: 'Steady title',
    },
    {
      albumId: albumMap['Steady'],
      trackNumber: 2,
      title: '3분까진 필요없어 (3 Minutes)',
      durationSec: 2 * 60 + 47,
      genre: 'Dance',
      language: 'KOREAN' as const,
      isTitle: false,
      isSingle: false,
      isPreRelease: false,
      releaseDate: new Date('2024-09-24'),
      hasMv: true,
      mvUrl: 'https://youtu.be/GTFqQDZ6jec',
      audioUrl: 'https://youtu.be/rEDmIVUK1TU0',
      note: null,
    },
    {
      albumId: albumMap['Steady'],
      trackNumber: 3,
      title: 'Dunk Shot',
      durationSec: 2 * 60 + 59,
      genre: 'Dance',
      language: 'KOREAN' as const,
      isTitle: false,
      isSingle: false,
      isPreRelease: true,
      releaseDate: new Date('2024-09-09'),
      hasMv: true,
      mvUrl: 'https://youtu.be/4vgac97VlCE',
      audioUrl: 'https://youtu.be/qqWK1i9wnt4',
      note: 'Pre-release track',
    },
    {
      albumId: albumMap['Steady'],
      trackNumber: 4,
      title: 'On & On (점점 더 더)',
      durationSec: 3 * 60 + 3,
      genre: 'Dance',
      language: 'KOREAN' as const,
      isTitle: false,
      isSingle: false,
      isPreRelease: false,
      releaseDate: new Date('2024-09-24'),
      hasMv: false,
      audioUrl: 'https://youtu.be/dVLwxf5LNSg',
      note: 'Alternative R&B dance track',
    },
    {
      albumId: albumMap['Steady'],
      trackNumber: 5,
      title: 'Supercute',
      durationSec: 2 * 60 + 51,
      genre: 'Dance',
      language: 'KOREAN' as const,
      isTitle: false,
      isSingle: false,
      isPreRelease: false,
      releaseDate: new Date('2024-09-24'),
      hasMv: false,
      audioUrl: 'https://youtu.be/G0B76L_wKBM',
      note: null,
    },
    {
      albumId: albumMap['Steady'],
      trackNumber: 6,
      title: 'Skate',
      durationSec: 3 * 60 + 19,
      genre: 'Dance',
      language: 'KOREAN' as const,
      isTitle: false,
      isSingle: false,
      isPreRelease: false,
      releaseDate: new Date('2024-09-24'),
      hasMv: false,
      audioUrl: 'https://youtu.be/HEHd32HE8Co',
      note: 'Stage Video',
    },
    {
      albumId: albumMap['Steady'],
      trackNumber: 7,
      title: 'Hands Up (Korean Ver.)',
      durationSec: 3 * 60 + 15,
      genre: 'Dance',
      language: 'KOREAN' as const,
      isTitle: false,
      isSingle: true,
      isPreRelease: false,
      releaseDate: new Date('2024-09-24'),
      hasMv: false,
      audioUrl: 'https://youtu.be/BWk1NYg-QeQ',
      note: 'Korean version of pre-debut track',
    },

    // ==================== WISHFUL (13곡) ====================
    {
      albumId: albumMap['WISHFUL'],
      trackNumber: 1,
      title: 'Wishful Winter',
      durationSec: 3 * 60 + 9,
      genre: 'Ballad',
      language: 'JAPANESE' as const,
      isTitle: true,
      isSingle: false,
      isPreRelease: false,
      releaseDate: new Date('2024-11-27'),
      hasMv: true,
      mvUrl: 'https://youtu.be/NAhEwvI9TGE',
      audioUrl: 'https://youtu.be/5lyZJtvt880',
      note: 'Wishful Winter title track',
    },
    {
      albumId: albumMap['WISHFUL'],
      trackNumber: 2,
      title: 'WISH (Japanese Ver.)',
      durationSec: 3 * 60 + 6,
      genre: 'Dance',
      language: 'JAPANESE' as const,
      isTitle: false,
      isSingle: true,
      isPreRelease: false,
      releaseDate: new Date('2024-11-27'),
      hasMv: false,
      audioUrl: 'https://youtu.be/SJzPVrcEjT8',
      note: null,
    },
    {
      albumId: albumMap['WISHFUL'],
      trackNumber: 3,
      title: 'Songbird (Japanese Ver.)',
      durationSec: 3 * 60 + 2,
      genre: 'Dance',
      language: 'JAPANESE' as const,
      isTitle: false,
      isSingle: true,
      isPreRelease: false,
      releaseDate: new Date('2024-11-27'),
      hasMv: false,
      audioUrl: 'https://youtu.be/Bnth3pE1Pus',
      note: null,
    },
    {
      albumId: albumMap['WISHFUL'],
      trackNumber: 4,
      title: 'FAR AWAY',
      durationSec: 3 * 60 + 5,
      genre: 'Pop',
      language: 'JAPANESE' as const,
      isTitle: false,
      isSingle: false,
      isPreRelease: false,
      releaseDate: new Date('2024-11-27'),
      hasMv: false,
      audioUrl: 'https://youtu.be/F6z5pFEoSSs',
      note: null,
    },
    {
      albumId: albumMap['WISHFUL'],
      trackNumber: 5,
      title: 'We Go!',
      durationSec: 3 * 60 + 1,
      genre: 'Pop',
      language: 'JAPANESE' as const,
      isTitle: false,
      isSingle: true,
      isPreRelease: false,
      releaseDate: new Date('2024-11-27'),
      hasMv: false,
      audioUrl: 'https://youtu.be/JkvpOhzEnnE',
      note: null,
    },
    {
      albumId: albumMap['WISHFUL'],
      trackNumber: 6,
      title: 'Touchdown',
      durationSec: 3 * 60 + 13,
      genre: 'Dance',
      language: 'JAPANESE' as const,
      isTitle: false,
      isSingle: false,
      isPreRelease: false,
      releaseDate: new Date('2024-11-27'),
      hasMv: false,
      audioUrl: 'https://youtu.be/Gwes7rTpoRY',
      note: null,
    },
    {
      albumId: albumMap['WISHFUL'],
      trackNumber: 7,
      title: 'Hands Up',
      durationSec: 3 * 60 + 14,
      genre: 'Dance',
      language: 'JAPANESE' as const,
      isTitle: false,
      isSingle: true,
      isPreRelease: false,
      releaseDate: new Date('2024-11-27'),
      hasMv: false,
      audioUrl: 'https://youtu.be/hHdU2NvD88I',
      note: null,
    },
    {
      albumId: albumMap['WISHFUL'],
      trackNumber: 8,
      title: 'Sail Away (Japanese Ver.)',
      durationSec: 3 * 60 + 26,
      genre: 'Pop',
      language: 'JAPANESE' as const,
      isTitle: false,
      isSingle: true,
      isPreRelease: false,
      releaseDate: new Date('2024-11-27'),
      hasMv: false,
      audioUrl: 'https://youtu.be/RYuUciEJmko',
      note: null,
    },
    {
      albumId: albumMap['WISHFUL'],
      trackNumber: 9,
      title: 'CHOO CHOO',
      durationSec: 3 * 60 + 35,
      genre: 'Dance',
      language: 'JAPANESE' as const,
      isTitle: false,
      isSingle: false,
      isPreRelease: false,
      releaseDate: new Date('2024-11-27'),
      hasMv: false,
      audioUrl: 'https://youtu.be/yA1r0U-nojg',
      note: null,
    },
    {
      albumId: albumMap['WISHFUL'],
      trackNumber: 10,
      title: 'NASA',
      durationSec: 3 * 60 + 4,
      genre: 'Dance',
      language: 'JAPANESE' as const,
      isTitle: false,
      isSingle: false,
      isPreRelease: true,
      releaseDate: new Date('2024-11-27'),
      hasMv: false,
      audioUrl: 'https://youtu.be/noGjEgZ15PM',
      note: 'Pre-released as performance video',
    },
    {
      albumId: albumMap['WISHFUL'],
      trackNumber: 11,
      title: 'P.O.V',
      durationSec: 3 * 60 + 2,
      genre: 'Dance',
      language: 'JAPANESE' as const,
      isTitle: false,
      isSingle: false,
      isPreRelease: false,
      releaseDate: new Date('2024-11-27'),
      hasMv: false,
      audioUrl: 'https://youtu.be/89b5nlmE3nc',
      note: null,
    },
    {
      albumId: albumMap['WISHFUL'],
      trackNumber: 12,
      title: 'Tears Are Falling (Japanese Ver.)',
      durationSec: 3 * 60 + 5,
      genre: 'Ballad',
      language: 'JAPANESE' as const,
      isTitle: false,
      isSingle: true,
      isPreRelease: false,
      releaseDate: new Date('2024-11-27'),
      hasMv: false,
      audioUrl: 'https://youtu.be/sjT6pd8PJSM',
      note: null,
    },
    {
      albumId: albumMap['WISHFUL'],
      trackNumber: 13,
      title: 'Our Adventures',
      durationSec: 2 * 60 + 53,
      genre: 'Pop',
      language: 'JAPANESE' as const,
      isTitle: false,
      isSingle: false,
      isPreRelease: false,
      releaseDate: new Date('2024-11-27'),
      hasMv: false,
      audioUrl: 'https://youtu.be/kTGA3ov4Na0',
      note: null,
    },

    // ==================== poppop (6곡) ====================
    {
      albumId: albumMap['poppop'],
      trackNumber: 1,
      title: 'poppop',
      durationSec: 3 * 60 + 2,
      genre: 'Dance',
      language: 'KOREAN' as const,
      isTitle: true,
      isSingle: false,
      isPreRelease: false,
      releaseDate: new Date('2025-04-14'),
      hasMv: true,
      mvUrl: 'https://youtu.be/LNETckymbzk',
      audioUrl: 'https://youtu.be/sAwVsdQOogQ',
      note: null,
    },
    {
      albumId: albumMap['poppop'],
      trackNumber: 2,
      title: 'Melt Inside My Pocket',
      durationSec: 3 * 60 + 11,
      genre: 'Dance',
      language: 'KOREAN' as const,
      isTitle: false,
      isSingle: false,
      isPreRelease: false,
      releaseDate: new Date('2025-04-14'),
      hasMv: false,
      audioUrl: 'https://youtu.be/GIoDgHfQX6Y',
      note: null,
    },
    {
      albumId: albumMap['poppop'],
      trackNumber: 3,
      title: 'Design',
      durationSec: 2 * 60 + 5,
      genre: 'R&B/Soul',
      language: 'KOREAN' as const,
      isTitle: false,
      isSingle: false,
      isPreRelease: false,
      releaseDate: new Date('2025-04-14'),
      hasMv: false,
      audioUrl: 'https://youtu.be/nIH8J6wkzOo',
      note: null,
    },
    {
      albumId: albumMap['poppop'],
      trackNumber: 4,
      title: '1000',
      durationSec: 2 * 60 + 51,
      genre: 'Dance',
      language: 'KOREAN' as const,
      isTitle: false,
      isSingle: false,
      isPreRelease: false,
      releaseDate: new Date('2025-04-14'),
      hasMv: false,
      audioUrl: 'https://youtu.be/8GCSIIzFEg8',
      note: null,
    },
    {
      albumId: albumMap['poppop'],
      trackNumber: 5,
      title: 'Silly Dance',
      durationSec: 3 * 60 + 2,
      genre: 'Dance',
      language: 'KOREAN' as const,
      isTitle: false,
      isSingle: false,
      isPreRelease: false,
      releaseDate: new Date('2025-04-14'),
      hasMv: false,
      audioUrl: 'https://youtu.be/QZOrObTL_V8',
      note: null,
    },
    {
      albumId: albumMap['poppop'],
      trackNumber: 6,
      title: '만약 네가 4시에 온다면 (Still 3PM)',
      durationSec: 2 * 60 + 45,
      genre: 'Dance',
      language: 'KOREAN' as const,
      isTitle: false,
      isSingle: false,
      isPreRelease: false,
      releaseDate: new Date('2025-04-14'),
      hasMv: false,
      audioUrl: 'https://youtu.be/to6dnhwZb1E',
      note: null,
    },

    // ==================== COLOR (7곡) ====================
    {
      albumId: albumMap['COLOR'],
      trackNumber: 1,
      title: 'COLOR',
      durationSec: 3 * 60,
      genre: 'Dance',
      language: 'KOREAN' as const,
      isTitle: true,
      isSingle: false,
      isPreRelease: false,
      releaseDate: new Date('2025-09-01'),
      hasMv: true,
      mvUrl: 'https://youtu.be/28dAfmIAlCo',
      audioUrl: 'https://youtu.be/r4RQR3OHXqg',
      note: 'COLOR title track',
    },
    {
      albumId: albumMap['COLOR'],
      trackNumber: 2,
      title: 'Baby Blue',
      durationSec: 2 * 60 + 31,
      genre: 'Dance',
      language: 'KOREAN' as const,
      isTitle: false,
      isSingle: false,
      isPreRelease: true,
      releaseDate: new Date('2025-08-26'),
      hasMv: true,
      mvUrl: 'https://youtu.be/FBr4hA9L90s',
      audioUrl: 'https://youtu.be/rW55eTaEtj8',
      note: 'MV pre-release',
    },
    {
      albumId: albumMap['COLOR'],
      trackNumber: 3,
      title: 'Surf',
      durationSec: 3 * 60 + 4,
      genre: 'Dance',
      language: 'KOREAN' as const,
      isTitle: false,
      isSingle: false,
      isPreRelease: true,
      releaseDate: new Date('2025-08-12'),
      hasMv: true,
      mvUrl: 'https://youtu.be/1pyO6oNmACs',
      audioUrl: 'https://youtu.be/rd3vDNHHdNQ',
      note: 'Pre-release single',
    },
    {
      albumId: albumMap['COLOR'],
      trackNumber: 4,
      title: 'Cheat Code',
      durationSec: 3 * 60 + 1,
      genre: 'Dance',
      language: 'KOREAN' as const,
      isTitle: false,
      isSingle: false,
      isPreRelease: false,
      releaseDate: new Date('2025-09-01'),
      hasMv: false,
      audioUrl: 'https://youtu.be/4VvbSmlcGxo',
      note: null,
    },
    {
      albumId: albumMap['COLOR'],
      trackNumber: 5,
      title: 'Videohood',
      durationSec: 3 * 60 + 1,
      genre: 'Rap/Hip-hop',
      language: 'KOREAN' as const,
      isTitle: false,
      isSingle: false,
      isPreRelease: false,
      releaseDate: new Date('2025-09-01'),
      hasMv: false,
      audioUrl: 'https://youtu.be/5cIo87AEbeY',
      note: 'Video game themed - Features LOL reference "Ninjas hide on bush"',
    },
    {
      albumId: albumMap['COLOR'],
      trackNumber: 6,
      title: 'WICHU',
      durationSec: 3 * 60 + 28,
      genre: 'R&B/Soul',
      language: 'KOREAN' as const,
      isTitle: false,
      isSingle: false,
      isPreRelease: false,
      releaseDate: new Date('2025-09-01'),
      hasMv: false,
      audioUrl: 'https://youtu.be/BKJlyleaaqM',
      note: null,
    },
    {
      albumId: albumMap['COLOR'],
      trackNumber: 7,
      title: '고양이 릴스 (Reel-ationship)',
      durationSec: 3 * 60 + 9,
      genre: 'R&B/Soul',
      language: 'KOREAN' as const,
      isTitle: false,
      isSingle: false,
      isPreRelease: false,
      releaseDate: new Date('2025-09-01'),
      hasMv: false,
      audioUrl: 'https://youtu.be/KO2xk8JyCc4',
      note: null,
    },
  ]

  const createdTracks: Track[] = []
  const progress = new ProgressTracker('Seeding Tracks', tracks.length)

  for (const trackData of tracks) {
    try {
      if (!trackData.albumId) {
        logger.warning(`  ⚠️  Skipping track "${trackData.title}" - album not found`)
        continue
      }

      const track = await prisma.track.upsert({
        where: {
          albumId_trackNumber: {
            albumId: trackData.albumId,
            trackNumber: trackData.trackNumber,
          },
        },
        update: trackData,
        create: trackData,
      })

      createdTracks.push(track)
      progress.increment()
    } catch (error) {
      logger.error(`Failed to seed track: ${trackData.title}`)
      throw error
    }
  }

  // 트랙 버전 관계 설정
  await linkTrackVersions(prisma, createdTracks)

  progress.complete()
  return createdTracks
}

async function linkTrackVersions(prisma: PrismaClient, tracks: Track[]) {
  const versionPairs: Array<[string, string]> = [
    ['WISH (Korean Ver.)', 'WISH (Japanese Ver.)'],
    ['Songbird (Korean Ver.)', 'Songbird (Japanese Ver.)'],
    ['Hands Up (Japanese Ver.)', 'Hands Up (Korean Ver.)'],
  ]

  for (const [originalTitle, versionTitle] of versionPairs) {
    const original = tracks.find((t) => t.title === originalTitle)
    const version = tracks.find((t) => t.title === versionTitle)

    if (original && version) {
      await prisma.track.update({
        where: { id: version.id },
        data: { originalTrackId: original.id },
      })
      logger.debug(`  🔗 Linked ${versionTitle} to ${originalTitle}`)
    }
  }
}