/**
 * Seed: 2025 NCT WISH Activities
 * Period: 2025.01 - 2025.12
 * Description: Complete annual activities including releases, tours, broadcasts, and award shows
 */

import { PrismaClient, EventType } from '@prisma/client';

export async function seed2025Events(prisma: PrismaClient) {
  console.log('🎊 Seeding 2025 Annual Activities...');

  const events = [
    // ========== JANUARY 2025 ==========
    // LOG in Tour continuation (Japan)
    {
      type: EventType.CONCERT,
      date: new Date('2025-01-03'),
      title: 'NCT WISH ASIA TOUR LOG in - 효고 (Day 1)',
      location: '고베 월드 기념홀',
      country: '일본',
      city: '효고',
      description: '2024-2025 LOG in 투어 연장 일정',
      isPreDebut: false,
    },
    {
      type: EventType.CONCERT,
      date: new Date('2025-01-04'),
      title: 'NCT WISH ASIA TOUR LOG in - 효고 (Day 2)',
      location: '고베 월드 기념홀',
      country: '일본',
      city: '효고',
      description: '2024-2025 LOG in 투어 연장 일정',
      isPreDebut: false,
    },
    {
      type: EventType.AWARD_SHOW,
      date: new Date('2025-01-05'),
      title: '제39회 골든디스크어워즈 (Golden Disc Awards)',
      location: '미즈호 PayPay 돔',
      country: '일본',
      city: '후쿠오카',
      description: '시상식 참석 및 무대',
      isPreDebut: false,
    },
    {
      type: EventType.CONCERT,
      date: new Date('2025-01-11'),
      title: 'SMTOWN LIVE 2025 in SEOUL (Day 1)',
      location: '고척 스카이돔',
      country: '한국',
      city: '서울',
      description: 'SMTOWN 30주년 기념 콘서트',
      isPreDebut: false,
    },
    {
      type: EventType.CONCERT,
      date: new Date('2025-01-12'),
      title: 'SMTOWN LIVE 2025 in SEOUL (Day 2)',
      location: '고척 스카이돔',
      country: '한국',
      city: '서울',
      description: 'SMTOWN 30주년 기념 콘서트',
      isPreDebut: false,
    },
    {
      type: EventType.CONCERT,
      date: new Date('2025-01-17'),
      title: 'NCT WISH ASIA TOUR LOG in - 도쿄 (Day 1)',
      location: '국립 요요기 경기장 제1체육관',
      country: '일본',
      city: '도쿄',
      description: '2024-2025 LOG in 투어 연장 일정',
      isPreDebut: false,
    },
    {
      type: EventType.CONCERT,
      date: new Date('2025-01-18'),
      title: 'NCT WISH ASIA TOUR LOG in - 도쿄 (Day 2)',
      location: '국립 요요기 경기장 제1체육관',
      country: '일본',
      city: '도쿄',
      description: '2024-2025 LOG in 투어 연장 일정',
      isPreDebut: false,
    },
    {
      type: EventType.RELEASE,
      date: new Date('2025-01-22'),
      title: 'Miracle (슈퍼주니어 리메이크) 디지털 싱글 발매',
      location: null,
      country: '한국',
      city: null,
      description: 'SMTOWN 30주년 프로젝트 - SM Town: The Culture, the Future',
      isPreDebut: false,
    },

    // ========== FEBRUARY 2025 ==========
    {
      type: EventType.AWARD_SHOW,
      date: new Date('2025-02-22'),
      title: '제1회 디 어워즈 (The 1st D Awards)',
      location: '고려대학교 화정체육관',
      country: '한국',
      city: '서울',
      description: '시상식 참석',
      isPreDebut: false,
    },

    // ========== MARCH 2025 ==========
    {
      type: EventType.CONCERT,
      date: new Date('2025-03-21'),
      title: 'NCT WISH ASIA TOUR LOG in in SEOUL (Day 1)',
      location: '올림픽공원 핸드볼경기장',
      country: '한국',
      city: '서울',
      description: '서울 단독 콘서트 - 금의환향 무대',
      isPreDebut: false,
    },
    {
      type: EventType.CONCERT,
      date: new Date('2025-03-22'),
      title: 'NCT WISH ASIA TOUR LOG in in SEOUL (Day 2)',
      location: '올림픽공원 핸드볼경기장',
      country: '한국',
      city: '서울',
      description: '서울 단독 콘서트',
      isPreDebut: false,
    },
    {
      type: EventType.CONCERT,
      date: new Date('2025-03-23'),
      title: 'NCT WISH ASIA TOUR LOG in in SEOUL (Day 3)',
      location: '올림픽공원 핸드볼경기장',
      country: '한국',
      city: '서울',
      description: '서울 단독 콘서트 - Poppop 신곡 무대 선공개',
      isPreDebut: false,
    },
    {
      type: EventType.RELEASE,
      date: new Date('2025-03-28'),
      title: 'Make You Shine (English Ver.) OST 발매',
      location: null,
      country: '한국',
      city: null,
      description: '포켓몬스터: 테라스탈 데뷔 OST',
      isPreDebut: false,
    },

    // ========== APRIL 2025 ==========
    {
      type: EventType.CONCERT,
      date: new Date('2025-04-04'),
      title: 'NCT WISH ASIA TOUR LOG in in MACAU (Day 1)',
      location: '브로드웨이 시어터',
      country: '마카오',
      city: '마카오',
      description: 'LOG in 투어 마카오 공연',
      isPreDebut: false,
    },
    {
      type: EventType.CONCERT,
      date: new Date('2025-04-05'),
      title: 'NCT WISH ASIA TOUR LOG in in MACAU (Day 2)',
      location: '브로드웨이 시어터',
      country: '마카오',
      city: '마카오',
      description: 'LOG in 투어 마카오 공연',
      isPreDebut: false,
    },
    {
      type: EventType.CONCERT,
      date: new Date('2025-04-06'),
      title: 'NCT WISH ASIA TOUR LOG in in MACAU (Day 3)',
      location: '브로드웨이 시어터',
      country: '마카오',
      city: '마카오',
      description: 'LOG in 투어 마카오 공연',
      isPreDebut: false,
    },
    {
      type: EventType.CONCERT,
      date: new Date('2025-04-12'),
      title: 'NCT WISH ASIA TOUR LOG in in MANILA',
      location: '뉴 프론티어 시어터',
      country: '필리핀',
      city: '마닐라',
      description: 'LOG in 투어 마닐라 공연',
      isPreDebut: false,
    },
    {
      type: EventType.RELEASE,
      date: new Date('2025-04-14'),
      title: 'Poppop 미니 2집 발매',
      location: null,
      country: '한국',
      city: null,
      description: '타이틀곡 Poppop - 청량 & 힐링 콘셉트',
      isPreDebut: false,
    },
    {
      type: EventType.SHOWCASE,
      date: new Date('2025-04-15'),
      title: 'Poppop in the bubble 쇼케이스',
      location: '송도 달빛축제공원',
      country: '한국',
      city: '인천',
      description: '야외 쇼케이스 - 봄 시즌 맞춤 기획',
      isPreDebut: false,
    },
    {
      type: EventType.OTHER,
      date: new Date('2025-04-30'),
      title: '서울 스프링 페스타: 원더쇼 (Wonder Show)',
      location: '서울월드컵경기장',
      country: '한국',
      city: '서울',
      description: '페스티벌 무대',
      isPreDebut: false,
    },

    // ========== MAY 2025 ==========
    {
      type: EventType.CONCERT,
      date: new Date('2025-05-02'),
      title: 'NCT WISH ASIA TOUR LOG in in HONG KONG (Day 1)',
      location: '아시아월드 엑스포 Hall 10',
      country: '홍콩',
      city: '홍콩',
      description: 'LOG in 투어 홍콩 공연',
      isPreDebut: false,
    },
    {
      type: EventType.CONCERT,
      date: new Date('2025-05-03'),
      title: 'NCT WISH ASIA TOUR LOG in in HONG KONG (Day 2)',
      location: '아시아월드 엑스포 Hall 10',
      country: '홍콩',
      city: '홍콩',
      description: 'LOG in 투어 홍콩 공연',
      isPreDebut: false,
    },
    {
      type: EventType.CONCERT,
      date: new Date('2025-05-09'),
      title: 'SMTOWN LIVE 2025 in MEXICO CITY',
      location: 'Estadio GNP Seguros',
      country: '멕시코',
      city: '멕시코시티',
      description: 'SMTOWN 글로벌 투어 - 북미 시장 진출',
      isPreDebut: false,
    },
    {
      type: EventType.CONCERT,
      date: new Date('2025-05-11'),
      title: 'SMTOWN LIVE 2025 in L.A.',
      location: 'Dignity Health Sports Park',
      country: '미국',
      city: 'LA',
      description: 'SMTOWN 글로벌 투어 - 북미 시장 진출',
      isPreDebut: false,
    },
    {
      type: EventType.CONCERT,
      date: new Date('2025-05-17'),
      title: 'NCT WISH ASIA TOUR LOG in in SINGAPORE',
      location: 'Arena @ Expo',
      country: '싱가포르',
      city: '싱가포르',
      description: 'LOG in 투어 싱가포르 공연',
      isPreDebut: false,
    },
    {
      type: EventType.FANMEETING,
      date: new Date('2025-05-19'),
      title: 'Poppop 1:1 영상통화 팬사인회',
      location: '온라인',
      country: '한국',
      city: null,
      description: '영통 팬사인회 (19:00 KST)',
      isPreDebut: false,
    },
    {
      type: EventType.CONCERT,
      date: new Date('2025-05-24'),
      title: 'NCT WISH ASIA TOUR LOG in in TAIPEI',
      location: '뮤직 센터',
      country: '대만',
      city: '타이베이',
      description: 'LOG in 투어 타이베이 공연',
      isPreDebut: false,
    },
    {
      type: EventType.AWARD_SHOW,
      date: new Date('2025-05-28'),
      title: '아시아 스타 엔터테이너 어워즈 2025 (ASEA)',
      location: 'K-아레나',
      country: '일본',
      city: '요코하마',
      description: '시상식 참석',
      isPreDebut: false,
    },
    {
      type: EventType.FANMEETING,
      date: new Date('2025-05-29'),
      title: '자카르타 대면 팬사인회',
      location: '자카르타 현지',
      country: '인도네시아',
      city: '자카르타',
      description: '대면 팬사인회',
      isPreDebut: false,
    },
    {
      type: EventType.CONCERT,
      date: new Date('2025-05-31'),
      title: 'NCT WISH ASIA TOUR LOG in in JAKARTA',
      location: '테니스 인도어 세나얀',
      country: '인도네시아',
      city: '자카르타',
      description: 'LOG in 투어 자카르타 공연',
      isPreDebut: false,
    },

    // ========== JUNE 2025 ==========
    {
      type: EventType.CONCERT,
      date: new Date('2025-06-07'),
      title: 'NCT WISH ASIA TOUR LOG in in BANGKOK (TOUR FINALE)',
      location: '썬더돔',
      country: '태국',
      city: '방콕',
      description: 'LOG in 투어 피날레 - 7개월 대장정 마무리',
      isPreDebut: false,
    },
    {
      type: EventType.OTHER,
      date: new Date('2025-06-11'),
      title: '2025 부산원아시아페스티벌 (BOF) BIG 콘서트',
      location: '벡스코(BEXCO)',
      country: '한국',
      city: '부산',
      description: '페스티벌 무대',
      isPreDebut: false,
    },
    {
      type: EventType.OTHER,
      date: new Date('2025-06-15'),
      title: '유튜브 팬페스트 코리아 2025 (YouTube Fanfest)',
      location: 'KBS아레나',
      country: '한국',
      city: '서울',
      description: '유튜브 공식 행사',
      isPreDebut: false,
    },
    {
      type: EventType.AWARD_SHOW,
      date: new Date('2025-06-21'),
      title: '제34회 서울가요대상 2024 (Seoul Music Awards)',
      location: '인스파이어 아레나',
      country: '한국',
      city: '인천',
      description: '시상식 참석',
      isPreDebut: false,
    },
    {
      type: EventType.CONCERT,
      date: new Date('2025-06-28'),
      title: 'SMTOWN LIVE 2025 in LONDON',
      location: 'O2 아레나',
      country: '영국',
      city: '런던',
      description: 'SMTOWN 글로벌 투어 - 유럽 진출',
      isPreDebut: false,
    },

    // ========== JULY 2025 ==========
    {
      type: EventType.MUSIC_SHOW,
      date: new Date('2025-07-06'),
      title: '쇼! 음악중심 in JAPAN',
      location: '베루나 돔',
      country: '일본',
      city: '사이타마',
      description: '일본 특집 방송',
      isPreDebut: false,
    },
    {
      type: EventType.MUSIC_SHOW,
      date: new Date('2025-07-26'),
      title: '2025 SBS 가요대전: Summer',
      location: '킨텍스(KINTEX)',
      country: '한국',
      city: '고양',
      description: '여름 특집 가요대전',
      isPreDebut: false,
    },
    {
      type: EventType.OTHER,
      date: new Date('2025-07-29'),
      title: 'SUMMER DANCE MUSIC FES.',
      location: '엑스포 아레나 마쓰리',
      country: '일본',
      city: '오사카',
      description: '댄스 뮤직 페스티벌',
      isPreDebut: false,
    },

    // ========== AUGUST 2025 ==========
    {
      type: EventType.CONCERT,
      date: new Date('2025-08-09'),
      title: 'SMTOWN LIVE 2025 in TOKYO (Day 1)',
      location: '도쿄 돔',
      country: '일본',
      city: '도쿄',
      description: 'SMTOWN 도쿄돔 공연',
      isPreDebut: false,
    },
    {
      type: EventType.CONCERT,
      date: new Date('2025-08-10'),
      title: 'SMTOWN LIVE 2025 in TOKYO (Day 2)',
      location: '도쿄 돔',
      country: '일본',
      city: '도쿄',
      description: 'SMTOWN 도쿄돔 공연',
      isPreDebut: false,
    },
    {
      type: EventType.OTHER,
      date: new Date('2025-08-16'),
      title: 'NCT WISH 썸머 스테이지',
      location: '캐리비안 베이 야외 파도풀 특설 무대',
      country: '한국',
      city: '용인',
      description: '여름 시즌 팬 이벤트',
      isPreDebut: false,
    },
    {
      type: EventType.AWARD_SHOW,
      date: new Date('2025-08-21'),
      title: '2025 케이 월드 드림 어워즈 (K World Dream Awards)',
      location: '잠실실내체육관',
      country: '한국',
      city: '서울',
      description: '시상식 참석',
      isPreDebut: false,
    },
    {
      type: EventType.AWARD_SHOW,
      date: new Date('2025-08-23'),
      title: '2025 텐센트 뮤직 엔터테인먼트 어워즈 (TMEA)',
      location: '갤럭시 아레나',
      country: '마카오',
      city: '마카오',
      description: '시상식 참석',
      isPreDebut: false,
    },
    {
      type: EventType.OTHER,
      date: new Date('2025-08-31'),
      title: 'a-nation 2025',
      location: '아지노모토 스타디움',
      country: '일본',
      city: '도쿄',
      description: '일본 최대 음악 페스티벌',
      isPreDebut: false,
    },

    // ========== SEPTEMBER 2025 ==========
    {
      type: EventType.RELEASE,
      date: new Date('2025-09-01'),
      title: 'COLOR 미니 3집 발매',
      location: null,
      country: '한국',
      city: null,
      description: '타이틀곡 Color - 음악적 성장과 변곡점',
      isPreDebut: false,
    },
    {
      type: EventType.SHOWCASE,
      date: new Date('2025-09-02'),
      title: 'NCT WISH COLOR PALETTE 쇼케이스',
      location: 'COEX',
      country: '한국',
      city: '서울',
      description: 'COLOR 앨범 쇼케이스 (20:00)',
      isPreDebut: false,
    },
    {
      type: EventType.AWARD_SHOW,
      date: new Date('2025-09-20'),
      title: '2025 더팩트 뮤직 어워즈 (TMA)',
      location: '아웃도어 퍼포먼스 베뉴',
      country: '마카오',
      city: '마카오',
      description: '시상식 참석 및 무대',
      isPreDebut: false,
    },

    // ========== OCTOBER 2025 ==========
    {
      type: EventType.OTHER,
      date: new Date('2025-10-10'),
      title: '2025 APEC 뮤직 페스타',
      location: '경주시민운동장',
      country: '한국',
      city: '경주',
      description: 'APEC 기념 음악 행사',
      isPreDebut: false,
    },
    {
      type: EventType.RELEASE,
      date: new Date('2025-10-17'),
      title: '이 세상 끝까지 OST 발매',
      location: null,
      country: '한국',
      city: null,
      description: '드라마 우주메리미 OST',
      isPreDebut: false,
    },
    {
      type: EventType.CONCERT,
      date: new Date('2025-10-31'),
      title: 'NCT WISH 1st CONCERT TOUR Into The Wish - 인천 (Day 1)',
      location: '인스파이어 아레나',
      country: '한국',
      city: '인천',
      description: '첫 단독 투어 개막 - 아레나급 공연장 입성',
      isPreDebut: false,
    },

    // ========== NOVEMBER 2025 ==========
    {
      type: EventType.CONCERT,
      date: new Date('2025-11-01'),
      title: 'NCT WISH 1st CONCERT TOUR Into The Wish - 인천 (Day 2)',
      location: '인스파이어 아레나',
      country: '한국',
      city: '인천',
      description: '첫 단독 투어',
      isPreDebut: false,
    },
    {
      type: EventType.CONCERT,
      date: new Date('2025-11-02'),
      title: 'NCT WISH 1st CONCERT TOUR Into The Wish - 인천 (Day 3)',
      location: '인스파이어 아레나',
      country: '한국',
      city: '인천',
      description: '첫 단독 투어',
      isPreDebut: false,
    },
    {
      type: EventType.CONCERT,
      date: new Date('2025-11-08'),
      title: 'Into The Wish Japan Tour - 이시카와 (Day 1)',
      location: '혼다 노모리 홀',
      country: '일본',
      city: '이시카와',
      description: '일본 홀 투어',
      isPreDebut: false,
    },
    {
      type: EventType.CONCERT,
      date: new Date('2025-11-09'),
      title: 'Into The Wish Japan Tour - 이시카와 (Day 2)',
      location: '혼다 노모리 홀',
      country: '일본',
      city: '이시카와',
      description: '일본 홀 투어',
      isPreDebut: false,
    },
    {
      type: EventType.CONCERT,
      date: new Date('2025-11-15'),
      title: 'Into The Wish Japan Tour - 히로시마',
      location: '히로시마 문화학원 HBG 홀',
      country: '일본',
      city: '히로시마',
      description: '일본 홀 투어',
      isPreDebut: false,
    },
    {
      type: EventType.CONCERT,
      date: new Date('2025-11-16'),
      title: 'Into The Wish Japan Tour - 카가와',
      location: '선포트 홀 다카마쓰',
      country: '일본',
      city: '카가와',
      description: '일본 홀 투어',
      isPreDebut: false,
    },
    {
      type: EventType.CONCERT,
      date: new Date('2025-11-21'),
      title: 'Into The Wish Japan Tour - 오사카 (Day 1)',
      location: '오릭스 극장',
      country: '일본',
      city: '오사카',
      description: '일본 홀 투어',
      isPreDebut: false,
    },
    {
      type: EventType.CONCERT,
      date: new Date('2025-11-22'),
      title: 'Into The Wish Japan Tour - 오사카 (Day 2)',
      location: '오릭스 극장',
      country: '일본',
      city: '오사카',
      description: '일본 홀 투어',
      isPreDebut: false,
    },
    {
      type: EventType.CONCERT,
      date: new Date('2025-11-23'),
      title: 'Into The Wish Japan Tour - 오사카 (Day 3)',
      location: '오릭스 극장',
      country: '일본',
      city: '오사카',
      description: '일본 홀 투어',
      isPreDebut: false,
    },
    {
      type: EventType.AWARD_SHOW,
      date: new Date('2025-11-28'),
      title: '2025 MAMA AWARDS',
      location: '카이탁 스타디움',
      country: '홍콩',
      city: '홍콩',
      description: 'Hearts2Hearts 콜라보 무대',
      isPreDebut: false,
    },
    {
      type: EventType.CONCERT,
      date: new Date('2025-11-29'),
      title: 'Into The Wish Japan Tour - 홋카이도',
      location: '가나모토 홀',
      country: '일본',
      city: '홋카이도',
      description: '일본 홀 투어',
      isPreDebut: false,
    },

    // ========== DECEMBER 2025 ==========
    {
      type: EventType.RELEASE,
      date: new Date('2025-12-11'),
      title: '프린세스 캐치! 티니핑 : 프린스핑송 OST 발매',
      location: null,
      country: '한국',
      city: null,
      description: '애니메이션 OST',
      isPreDebut: false,
    },
    {
      type: EventType.MUSIC_SHOW,
      date: new Date('2025-12-14'),
      title: '2025 뮤직뱅크 글로벌 페스티벌 in JAPAN',
      location: '도쿄 국립경기장',
      country: '일본',
      city: '도쿄',
      description: '뮤직뱅크 일본 특집',
      isPreDebut: false,
    },
    {
      type: EventType.CONCERT,
      date: new Date('2025-12-18'),
      title: 'Into The Wish Japan Tour - 후쿠오카 (Day 1)',
      location: '후쿠오카 선팰리스',
      country: '일본',
      city: '후쿠오카',
      description: '일본 홀 투어',
      isPreDebut: false,
    },
    {
      type: EventType.CONCERT,
      date: new Date('2025-12-19'),
      title: 'Into The Wish Japan Tour - 후쿠오카 (Day 2)',
      location: '후쿠오카 선팰리스',
      country: '일본',
      city: '후쿠오카',
      description: '일본 홀 투어',
      isPreDebut: false,
    },
    {
      type: EventType.AWARD_SHOW,
      date: new Date('2025-12-20'),
      title: '2025 멜론 뮤직 어워드 (MMA)',
      location: '고척 스카이돔',
      country: '한국',
      city: '서울',
      description: '2관왕 달성 (TOP 10, 카카오뱅크 모두의 스타상)',
      isPreDebut: false,
    },
    {
      type: EventType.CONCERT,
      date: new Date('2025-12-21'),
      title: 'Into The Wish Japan Tour - 아이치 (Day 1)',
      location: '아이치 현립 예술극장',
      country: '일본',
      city: '아이치',
      description: '일본 홀 투어',
      isPreDebut: false,
    },
    {
      type: EventType.CONCERT,
      date: new Date('2025-12-22'),
      title: 'Into The Wish Japan Tour - 아이치 (Day 2)',
      location: '아이치 현립 예술극장',
      country: '일본',
      city: '아이치',
      description: '일본 홀 투어',
      isPreDebut: false,
    },
    {
      type: EventType.CONCERT,
      date: new Date('2025-12-23'),
      title: 'Into The Wish Japan Tour - 아이치 (Day 3)',
      location: '아이치 현립 예술극장',
      country: '일본',
      city: '아이치',
      description: '일본 홀 투어',
      isPreDebut: false,
    },
    {
      type: EventType.MUSIC_SHOW,
      date: new Date('2025-12-25'),
      title: '2025 SBS 가요대전 (Gayo Daejeon)',
      location: 'SBS 방송센터',
      country: '한국',
      city: '서울',
      description: '크리스마스 특집 가요대전',
      isPreDebut: false,
    },
    {
      type: EventType.MUSIC_SHOW,
      date: new Date('2025-12-31'),
      title: '2025 MBC 가요대제전',
      location: 'MBC 방송센터',
      country: '한국',
      city: '서울',
      description: '연말 가요대제전',
      isPreDebut: false,
    },
  ];

  const created = await prisma.event.createMany({
    data: events,
    skipDuplicates: true,
  });

  console.log(`✅ 2025 Activities: ${created.count} records created`);
  return events;
}
