// prisma/seeds/05-events-2025.ts
import {
  EventType,
  ContentType,
  Platform,
  ExternalLinkType,
} from "@prisma/client";
import type { EventInput } from "../types-event";

export const events202504: EventInput[] = [
  // ==========================================
  // APRIL 2025
  // ==========================================
  {
    date: "2025-04-04",
    time: "20:00",
    type: EventType.TOUR,
    title: "[Tour] 2025 NCT WISH ASIA TOUR LOG in MACAU (Day 1)",
    location: "브로드웨이 시어터 (Broadway Theatre)",
    country: "MO",
    city: "마카오 (Macau)",
    seriesName: "NCT WISH ASIA TOUR LOG in",
  },
  {
    date: "2025-04-05",
    type: EventType.BIRTHDAY,
    title: "[Birthday] 유우시 생일",
    description: "Happy YUSHI Day💙",
    participants: {
      type: "ONLY",
      memberNames: ["유우시"],
    },
  },
  {
    date: "2025-04-05",
    time: "20:00",
    type: EventType.TOUR,
    title: "[Tour] 2025 NCT WISH ASIA TOUR LOG in MACAU (Day 2)",
    location: "브로드웨이 시어터 (Broadway Theatre)",
    country: "MO",
    city: "마카오 (Macau)",
    seriesName: "NCT WISH ASIA TOUR LOG in",
  },
  {
    date: "2025-04-06",
    time: "17:00",
    type: EventType.TOUR,
    title: "[Tour] 2025 NCT WISH ASIA TOUR LOG in MACAU (Day 3)",
    location: "브로드웨이 시어터 (Broadway Theatre)",
    country: "MO",
    city: "마카오 (Macau)",
    seriesName: "NCT WISH ASIA TOUR LOG in",
  },
  {
    date: "2025-04-12",
    time: "19:00",
    type: EventType.TOUR,
    title: "[Tour] 2025 NCT WISH ASIA TOUR LOG in MANILA",
    location: "뉴 프론티어 시어터 (New Frontier Theater)",
    country: "PH",
    city: "마닐라 (Manila)",
    seriesName: "NCT WISH ASIA TOUR LOG in",
  },
  {
    date: "2025-04-14",
    time: "18:00",
    type: EventType.RELEASE,
    title: "[Album] The 2nd Mini Album 《poppop》발매",
    country: "KR",
    albumTitle: "poppop",
    externalLinks: [
      {
        type: ExternalLinkType.OFFICIAL,
        url: "https://nct-jp.net/en/news/detail.php?id=1123651",
        label: "발매 공지",
      },
    ],
  },
  {
    date: "2025-04-14",
    time: "18:30",
    type: EventType.EVENT,
    title: "[Event] 멜론뮤직 MUSIC WAVE 채팅 이벤트",
    country: "KR",
    albumTitle: "poppop",
  },
  {
    date: "2025-04-14",
    time: "20:50",
    type: EventType.VARIETY_SHOW,
    title: "[JTBC] 톡파원 25시",
    country: "KR",
    participants: {
      type: "ONLY",
      memberNames: ["시온", "사쿠야"],
      role: "Guest",
    },
  },
  {
    date: "2025-04-15",
    time: "12:00",
    type: EventType.SHOWCASE,
    title: "[Showcase] poppop in the bubble - 1회",
    country: "KR",
    albumTitle: "poppop",
    location: "송도 달빛축제공원",
    city: "인천 (Incheon)",
  },
  {
    date: "2025-04-15",
    time: "14:00",
    type: EventType.SHOWCASE,
    title: "[Showcase] poppop in the bubble - 2회",
    country: "KR",
    albumTitle: "poppop",
    location: "송도 달빛축제공원",
    city: "인천 (Incheon)",
  },
  {
    date: "2025-04-15",
    time: "16:00",
    type: EventType.SHOWCASE,
    title: "[Showcase] poppop in the bubble - 3회",
    country: "KR",
    albumTitle: "poppop",
    location: "송도 달빛축제공원",
    city: "인천 (Incheon)",
  },
  {
    date: "2025-04-17",
    time: "18:00",
    type: EventType.MUSIC_SHOW,
    title: "[Mnet] 엠카운트다운",
    country: "KR",
    albumTitle: "poppop",
    appearance: {
      programName: "엠카운트다운",
    },
  },
  {
    date: "2025-04-18",
    time: "17:05",
    type: EventType.MUSIC_SHOW,
    title: "[KBS2] 뮤직뱅크",
    country: "KR",
    albumTitle: "poppop",
    appearance: {
      programName: "뮤직뱅크",
    },
  },
  {
    date: "2025-04-18",
    time: "20:00",
    type: EventType.FANSIGN,
    title: "[Fansign] 'popppop' 발매 기념 VIDEO CALL EVENT - 애플뮤직",
    description: "발매 기념 화상 팬사인회 진행",
  },
  {
    date: "2025-04-19",
    time: "15:15",
    type: EventType.MUSIC_SHOW,
    title: "[MBC] 쇼! 음악중심",
    country: "KR",
    albumTitle: "poppop",
    appearance: {
      programName: "쇼! 음악중심",
    },
  },
  {
    date: "2025-04-19",
    time: "18:00",
    type: EventType.FANSIGN,
    title: "[Fansign] 'poppop' 발매 기념 사인회 - 메이크스타",
    description: "발매 기념 대면 팬사인회 진행",
  },
  {
    date: "2025-04-20",
    time: "15:20",
    type: EventType.MUSIC_SHOW,
    title: "[SBS] 인기가요",
    country: "KR",
    albumTitle: "poppop",
    appearance: {
      programName: "인기가요",
    },
  },
  {
    date: "2025-04-20",
    time: "20:00",
    type: EventType.FANSIGN,
    title: "[Fansign] 'poppop' 발매 기념 사인회 - 뮤직아트",
    description: "발매 기념 대면 팬사인회 진행",
  },
  {
    date: "2025-04-20",
    time: "21:20",
    type: EventType.VARIETY_SHOW,
    title: "[KBS2] 개그콘서트",
    country: "KR",
    participants: {
      type: "ONLY",
      memberNames: ["시온", "재희"],
      role: "특별 출연",
    },
  },
  {
    date: "2025-04-21",
    time: "12:00",
    type: EventType.RADIO,
    title: "[KBS Cool FM] 이은지의 가요광장 (89.1MHz/보이는 라디오)",
    country: "KR",
    albumTitle: "poppop",
    appearance: {
      programName: "이은지의 가요광장",
      role: "Guest",
    },
  },
  {
    date: "2025-04-22",
    time: "19:00",
    type: EventType.FANSIGN,
    title: "[Fansign] 'popppop' 발매 기념 VIDEO CALL EVENT - 케이타운포유",
    description: "발매 기념 화상 팬사인회 진행",
  },
  {
    date: "2025-04-24",
    time: "18:00",
    type: EventType.MUSIC_SHOW,
    title: "[Mnet] 엠카운트다운",
    country: "KR",
    albumTitle: "poppop",
    appearance: {
      programName: "엠카운트다운",
    },
  },
  {
    date: "2025-04-24",
    time: "20:30",
    type: EventType.FANSIGN,
    title: "[Fansign] 'popppop' 발매 기념 VIDEO CALL EVENT - 점프업이엔티",
    description: "발매 기념 화상 팬사인회 진행",
  },
  {
    date: "2025-04-25",
    time: "17:05",
    type: EventType.MUSIC_SHOW,
    title: "[KBS2] 뮤직뱅크",
    country: "KR",
    albumTitle: "poppop",
    appearance: {
      programName: "뮤직뱅크",
    },
  },
  {
    date: "2025-04-26",
    time: "15:15",
    type: EventType.MUSIC_SHOW,
    title: "[MBC] 쇼! 음악중심",
    country: "KR",
    albumTitle: "poppop",
    appearance: {
      programName: "쇼! 음악중심",
    },
  },
  {
    date: "2025-04-26",
    time: "19:00",
    type: EventType.FANSIGN,
    title: "[Fansign] 'poppop' 발매 기념 사인회 - 뮤직아트",
    description: "발매 기념 대면 팬사인회 진행",
  },
  {
    date: "2025-04-28",
    time: "20:30",
    type: EventType.FANSIGN,
    title: "[Fansign] 'popppop' 발매 기념 VIDEO CALL EVENT - 디어마이뮤즈",
    description: "발매 기념 화상 팬사인회 진행",
  },
  {
    date: "2025-04-30",
    time: "19:00",
    type: EventType.FESTIVAL,
    title: "[Festival] 서울스프링페스타 WONDER SHOW",
    location: "상암 월드컵 경기장",
    country: "KR",
    city: "서울 (Seoul)",
  },
];
